sudo: required
language: c

compiler: gcc

install:
  sudo apt-get install -y gfortran mpich2 libmpich2-3 libmpich2-dev

script:
  - export
  - make testopenmp
  - make testpthread
  - test -n $CC && unset CC
  - make testmpi
  - make testmpiomp

notifications:
  email: false
