sudo: required
language: c

compiler: gcc

install:
  sudo apt-get install -y libcr-dev mpich2 mpich2-doc

script:
  - export
  - make testopenmp
  - make testpthread
  - test -n $CC && unset CC
  - make testmpi
  - make testmpiomp

notifications:
  email: false
