language: c

compiler: gcc

before_install:
  - export CUDA_VERSION=10.0.130-1
  - wget "http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/cuda-repo-ubuntu1404_${CUDA_VERSION}_amd64.deb"
  - sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/7fa2af80.pub
  - sudo dpkg -i cuda-repo-ubuntu1404_${CUDA_VERSION}_amd64.deb
  - sudo apt-get update
  - export CUDA_HOME=/usr/local/cuda-${CUDA_VERSION%%-*}
  - export LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}
  - export PATH=${CUDA_HOME}/bin:${PATH}

install:
  - sudo apt-get install -y libcr-dev mpich2 mpich2-doc
  - sudo apt-get install -y cuda

script:
  - make testopenmp
  - make testpthread
  - make cuda
  - test -n $CC && unset CC
  - make testmpi
  - make testmpiomp

notifications:
  email: false
